### ISSUE TITLE
Error when extracting files from an empty archive

### ISSUE THREAD

**Issue by simpadjo** [srikanth-lingala/zip4j#118]
version: "net.lingala.zip4j:zip4j:2.2.7"

I'm trying to extract the files from a zip archive

```
val zipFile = new ZipFile(new File("some/path"))
zipFile.extractAll("/tmp")
```

If the archive is an empty archive (the file has length of 22 bytes) this code crashes with the following error:

> Exception in thread "main" net.lingala.zip4j.exception.ZipException: java.io.IOException: Negative seek offset
> 	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:856)
> 	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:425)
> 	at 
> 	at .....
> Caused by: java.io.IOException: Negative seek offset
> 	at java.io.RandomAccessFile.seek(RandomAccessFile.java:555)
> 	at net.lingala.zip4j.headers.HeaderReader.setFilePointerToReadZip64EndCentralDirLoc(HeaderReader.java:529)
> 	at net.lingala.zip4j.headers.HeaderReader.readZip64EndOfCentralDirectoryLocator(HeaderReader.java:345)
> 	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:74)
> 	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:851)
> 	... 12 more

Sorry, not familiar with ZIP so can't help with the fix.

**Comment by srikanth-lingala** [comment]
Thanks for reporting the issue. I will include a fix in the next release.

**Comment by srikanth-lingala** [comment]
Fixed in v2.2.8 released today

**Comment by simpadjo** [comment]
@srikanth-lingala sorry, the problem still exists. 
Your fix rejects files which are strictly smaller than 22b but still fails on a perfectly valid empty archive of size 22b.

**Comment by srikanth-lingala** [comment]
You are right. I missed to consider this point in my previous fix. I fixed it. I will include the fix in the next release.

**Comment by simpadjo** [comment]
Works now, thank you!

**Comment by srikanth-lingala** [comment]
Fixed in v2.3.0 released today
