### ISSUE TITLE
crc failed wrong password error on one file while unzipping

### ISSUE THREAD

**Issue by pramodkr7** [srikanth-lingala/zip4j#276]
I have the zip file generated using zip4j-1.3.1 and it will be placed in the remote location, this file has more than 200 pdf files,while extracting it, I get crc failed wrong password? error on one pdf file while unzipping it through winzip, 7zip etc.

Password used to extract is the correct password, so there is no problem with the password

Below is the code used to create zip using zip4j.

for (File file : dir.listFiles()) {
	filesToAdd.add(file);
}

ZipParameters parameters = new ZipParameters();
parameters.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
parameters.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_NORMAL);
parameters.setEncryptFiles(true);
parameters.setEncryptionMethod(Zip4jConstants.ENC_METHOD_AES);
parameters.setAesKeyStrength(Zip4jConstants.AES_STRENGTH_256);
parameters.setPassword(this.getZipPassword());
zipFile.addFiles(filesToAdd, parameters);

Kindly help, Thanks in advance

**Comment by srikanth-lingala** [comment]
Can you please upgrade to the latest version of zip4j (v2.x) and see if it works? Zip4j v1.x had some bugs which were fixed in v2.x, and most likely this is fixed as well. Moreover I do not support v1.x anymore.

**Comment by pramodkr7** [comment]
I looked over all the issues reported here, and I couldn't find the one which is relevant, so I thought this might not be addressed in the later releases. I'll upgrade and check, if you know what could be causing this, please let me know, that'll help me a lot.

**Comment by HarishKumar7** [comment]
I am using the latest version of zip4j 2.6.4. Still facing this issue if I try to extract from third party app to extract files.

**Comment by pramodkr7** [comment]
@srikanth-lingala even with latest version we have this issue. Is there anything we are doing not right. @HarishKumar7 please post the code you used to zip

**Comment by pramodkr7** [comment]
@srikanth-lingala can you please assist me?

**Comment by srikanth-lingala** [comment]
Can you please post the code you are using to zip the file?

**Comment by HarishKumar7** [comment]
These are the areas where I made my changes. Please do needful. Thanks in Advance. 

in build.gradle

compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

implementation 'net.lingala.zip4j:zip4j:2.6.4'


filesToAdd is the arraylist of files passing to this method.                

               ZipParameters zipParameters = new ZipParameters();
		zipParameters.setEncryptFiles(true);
		zipParameters.setEncryptionMethod(EncryptionMethod.ZIP_STANDARD);
		File file;
		ZipFile zipFile = null;
		try {
			zipFile = new ZipFile(mFileName,"12345".toCharArray());
			zipFile.addFiles(filesToAdd,zipParameters);
		} catch (ZipException e) {
			e.printStackTrace();
		}

**Comment by pramodkr7** [comment]
@srikanth-lingala ,

This is how I am doing it,

for (File file : dir.listFiles()) {
filesToAdd.add(file);
}

ZipParameters parameters = new ZipParameters();
parameters.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
parameters.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_NORMAL);
parameters.setEncryptFiles(true);
parameters.setEncryptionMethod(Zip4jConstants.ENC_METHOD_AES);
parameters.setAesKeyStrength(Zip4jConstants.AES_STRENGTH_256);
parameters.setPassword("ABC123");
zipFile.addFiles(filesToAdd, parameters);

**Comment by srikanth-lingala** [comment]
@pramodkr7 Looks like you are still using the old version. Did you already try with the new version?

**Comment by srikanth-lingala** [comment]
BTW, will you be able to attach a sample zip file which has this issue?

**Comment by pramodkr7** [comment]
@srikanth-lingala , no it is over 500 MB and contains sensitive data :( .

**Comment by HarishKumar7** [comment]
@srikanth-lingala  I am using the latest version and add the relevant changes made for my project. I am facing this issue randomly. can you please help me with this?

**Comment by pramodkr7** [comment]
@HarishKumar7 , can you attach your zip which has the problem, i am not able to replicate it in my local may be because i dont have the huge data.

**Comment by srikanth-lingala** [comment]
@pramodkr7 Have you really tried this with the latest version of zip4j? If yes, can you post your code?

**Comment by srikanth-lingala** [comment]
I tried everything I could to reproduce this issue. I made 300 replicas of an 8 MB PDF file , and added all of them to a zip file with both AES, and ZIP_STANDARD encryption, and also without encryption. I generated this zip file several times in several ways (adding each file, adding directory, etc), and all my attempts were successful. I was successfully able to extract the zip file with zip4j, Keka (uses 7zip libraries underneath) and The Unarchiver. 

I really want to help investigate this issue and fix any bug, but without a way to reproduce this issue, it will be quite impossible to do something from my side.

**Comment by srikanth-lingala** [comment]
I have made a new release `v2.7.0` today which contains several fixes. Maybe try upgrading to that version to see if some fix also fixes this issue. If not, I really cannot help unless I find a way to reproduce this issue.

Unfortunately, I do not have any other option than to close this issue. Please feel free to reopen if you can let me know a way to reproduce this issue.
