### ISSUE TITLE
ZipInputStream stop finding next entry if entry is a folder with Data Descriptor

### ISSUE THREAD

**Issue by LeeYoung624** [srikanth-lingala/zip4j#309]
ZipInputStream stop finding next entry if entry is a folder with Data Descriptor. This zip could be extracted by `unzip` in Linux.

Seems this is caused by `ZipInputStream.readUntilEndOfEntry`
```
    if (localFileHeader.isDirectory()
        || (localFileHeader.getCompressedSize() == 0 && !localFileHeader.isDataDescriptorExists())) {
      return;
    }
```

**Comment by srikanth-lingala** [comment]
I will try to reproduce this

**Comment by srikanth-lingala** [comment]
Fixed in v2.8.0 released today.

**Comment by mbach979** [comment]
I believe this issue is still not fixed (tested in 2.9.0).   The attached simple example of writing a zip archive with just two directories using ZipOutputStream and then reading with ZipInputStream fails to read the second entry. 

The offending code seems to be in ZipInputStream.read(byte[], int, int) lines 155-157:
`
    if (localFileHeader.isDirectory()) {
      return -1;
    }
`
Since this stops reading before endOfCompressedDataRecord() can be called, and subsequently read the data descriptor block.   Reading the next entry then silently fails because the signature is for a data descriptor and not a local file header.

[Zip4jDirectoryDataDescriptorBug.zip](https://github.com/srikanth-lingala/zip4j/files/7093077/Zip4jDirectoryDataDescriptorBug.zip)
